version: '2'
services:
    gateway-cassandra:
        container_name: gateway-cassandra
        image: cassandra:3.9
        # volumes:
        #     - ~/volumes/jhipster/gateway/cassandra/:/var/lib/cassandra/data
        ports:
            - 7000:7000
            - 7001:7001
            - 7199:7199
            - 9042:9042
            - 9160:9160
    gateway-cassandra-node:
        image: cassandra:3.9
        links:
            - gateway-cassandra:seed
        environment:
            - CASSANDRA_SEEDS=seed
    gateway-cassandra-migration:
        extends:
            file: cassandra-migration.yml
            service: gateway-cassandra-migration
        links:
            - gateway-cassandra
        environment:
            - CREATE_KEYSPACE_SCRIPT=create-keyspace-prod.cql
